version: "3"
services:
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password

    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSOWRD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb

    application:
        image: my-app:1.0
        ports:
            - "8080:8080"
